name: You spin me right round, baby

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions: 
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install MinGW i686
        run: choco install mingw --x86 -y --no-progress

      - name: Update PATH
        run: echo C:/ProgramData/mingw64/mingw32/bin/ >> $env:GITHUB_PATH

      - name: Install SCFA-python-patcher
        run: |
          git clone https://github.com/4z0t/SCFA-python-patcher.git
          pip install -r ./SCFA-python-patcher/requirements.txt

      - name: Download Base
        run: curl -L "https://content.faforever.com/build/ForgedAlliance_base.exe" -o ForgedAlliance_base.exe

      - name: Patch ForgedAlliance_base.exe
        run: |
          echo "#define gitsha \"${{ github.sha }}\"" > workflow.cpp
          mkdir build
          python ./SCFA-python-patcher/main.py "$(pwd)" clang++ ld g++

      - name: Create new GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.sha }}"
          name: "Salam Release ${{ github.sha }}"
          body: "Test"
          files: |
            ForgedAlliance_exxt.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}